=== Egalvi/SurveyCore/model/src/main/resources/xsd/survey.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="https://www.egalvi.ru/survey"
           xmlns="https://www.egalvi.ru/survey"
           elementFormDefault="qualified">

    <xs:element name="survey">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="name" type="xs:string"/>
                <xs:element name="questions" type="questions"/>
                <xs:element name="keys" type="keys" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="questions">
        <xs:sequence>
            <xs:element name="question" type="question" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="question">
        <xs:sequence>
            <xs:element name="text" type="xs:string"/>
            <xs:element name="answer" type="answer" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="answer">
        <xs:sequence>
            <xs:element name="scale" type="scale" maxOccurs="unbounded"/>
            <xs:element name="text" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="scale">
        <xs:attribute name="name" type="xs:string"/>
        <xs:attribute name="value" type="xs:integer"/>
    </xs:complexType>

    <xs:complexType name="keys">
        <xs:sequence>
            <xs:element name="key" type="key" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="key">
        <xs:sequence>
            <xs:element name="scale" type="keyscale" maxOccurs="unbounded"/>
            <xs:element name="text" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="keyscale">
        <xs:attribute name="name" type="xs:string"/>
        <xs:attribute name="value" type="xs:integer"/>
        <xs:attribute name="minValueExclusive" type="xs:integer"/>
        <xs:attribute name="minValueInclusive" type="xs:integer"/>
        <xs:attribute name="maxValueExclusive" type="xs:integer"/>
        <xs:attribute name="maxValueInclusive" type="xs:integer"/>
    </xs:complexType>

</xs:schema>

=== Egalvi/SurveyCore/servicejaxb/src/test/resources/questions.xml
<survey xmlns="https://www.egalvi.ru/survey"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:schemaLocation="https://www.egalvi.ru/survey survey.xsd">
	<name>Test name</name>
	<questions>
		<question>
			<text>Question text</text>
			<answer>
				<scale name='scale1' value='+1' />
				<scale name='scale2' value='+1' />
				<scale name='scale3' value='+1' />
				<text>Answer text</text>
			</answer>
			<answer>
				<scale name='scale1' value='+1' />
				<scale name='scale2' value='+1' />
				<scale name='scale3' value='+1' />
				<text>Answer text</text>
			</answer>
			<answer>
				<scale name='scale1' value='+1' />
				<scale name='scale2' value='+1' />
				<scale name='scale3' value='+1' />
				<text>Answer text</text>
			</answer>
		</question>
		<question>
			<text>Question text</text>
			<answer>
				<scale name='scale1' value='+1' />
				<scale name='scale2' value='+1' />
				<scale name='scale3' value='+1' />
				<text>Answer text</text>
			</answer>
			<answer>
				<scale name='scale1' value='+1' />
				<scale name='scale2' value='+1' />
				<scale name='scale3' value='+1' />
				<text>Answer text</text>
			</answer>
			<answer>
				<scale name='scale1' value='+1' />
				<scale name='scale2' value='+1' />
				<scale name='scale3' value='+1' />
				<text>Answer text</text>
			</answer>
		</question>
	</questions>
	<keys>
		<key>
			<scale name='scale1' minValueInclusive='+1' maxValueExclusive="+5"/>
			<scale name='scale2' value='+1' />
			<scale name='scale3' value='+1' />
			<text>Answer text1</text>
		</key>
		<key>
			<scale name='scale1' value='+2' />
			<scale name='scale2' value='+2' />
			<scale name='scale3' value='+2' />
			<text>Answer text2</text>
		</key>
	</keys>
</survey>
